#!/usr/bin/env node

/**
 * Downloads Google Fonts for self-hosting
 * Uses google-webfonts-helper API to fetch optimized font files
 */

import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const WORKSPACE_ROOT = path.resolve(__dirname, "../..")
const OUTPUT_DIR = path.join(WORKSPACE_ROOT, "quartz/static/fonts")

// Font configurations matching quartz.config.ts
const FONTS = [
  {
    family: "Schibsted Grotesk",
    weights: [400, 700],
    styles: ["normal"],
  },
  {
    family: "Source Sans 3",
    weights: [400, 600],
    styles: ["normal", "italic"],
  },
  {
    family: "IBM Plex Mono",
    weights: [400],
    styles: ["normal"],
  },
]

async function downloadFont(fontConfig) {
  const { family, weights, styles } = fontConfig
  const familySlug = family.toLowerCase().replace(/\s+/g, "-")
  const fontDir = path.join(OUTPUT_DIR, familySlug)
  await fs.mkdir(fontDir, { recursive: true })

  console.log(`📥 Downloading ${family}...`)

  const cssRules = []

  // Download each weight/style combination
  for (const weight of weights) {
    for (const style of styles) {
      const isItalic = style === "italic"

      try {
        // Request font CSS from Google Fonts with woff2 user agent
        const fontUrl = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:${isItalic ? "ital," : ""}wght@${isItalic ? "1," : ""}${weight}&display=swap`

        console.log(`  ↓ ${weight}${isItalic ? " italic" : ""}...`)

        const cssResponse = await fetch(fontUrl, {
          headers: {
            // User agent that triggers woff2-only response
            "User-Agent":
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          },
        })

        if (!cssResponse.ok) {
          throw new Error(`HTTP ${cssResponse.status}: ${cssResponse.statusText}`)
        }

        const cssText = await cssResponse.text()

        // Extract woff2 URL from CSS
        const urlMatch = cssText.match(/url\((https:\/\/[^)]+\.woff2)\)/)
        if (!urlMatch) {
          console.warn(`  ⚠️  No woff2 URL found in CSS response`)
          continue
        }

        const woff2Url = urlMatch[1]
        const filename = `${familySlug}-${weight}${isItalic ? "-italic" : ""}.woff2`
        const filePath = path.join(fontDir, filename)

        // Download the woff2 file
        const fontResponse = await fetch(woff2Url)
        if (!fontResponse.ok) {
          throw new Error(`Failed to download font file: ${fontResponse.statusText}`)
        }

        const buffer = await fontResponse.arrayBuffer()
        await fs.writeFile(filePath, Buffer.from(buffer))

        // Generate CSS @font-face rule
        const cssRule = `
@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('/static/fonts/${familySlug}/${filename}') format('woff2');
}`

        cssRules.push(cssRule)
        console.log(`  ✓ ${filename}`)
      } catch (error) {
        console.error(`  ✗ Failed to download ${weight}${isItalic ? " italic" : ""}: ${error.message}`)
      }
    }
  }

  // Write CSS file for this font family
  if (cssRules.length > 0) {
    const cssPath = path.join(fontDir, `${familySlug}.css`)
    await fs.writeFile(cssPath, cssRules.join("\n"))
    console.log(`  ✓ Generated ${familySlug}.css\n`)
  } else {
    console.warn(`  ⚠️  No fonts downloaded for ${family}\n`)
  }
}

async function generateMasterCSS() {
  console.log("📝 Generating master fonts.css...")

  const imports = FONTS.map((font) => {
    const familySlug = font.family.toLowerCase().replace(/\s+/g, "-")
    return `@import url('/static/fonts/${familySlug}/${familySlug}.css');`
  })

  const masterCSS = `/**
 * Self-hosted Google Fonts
 * Generated by utils/fonts/download-fonts.mjs
 * 
 * Fonts included:
 * - Schibsted Grotesk (header)
 * - Source Sans 3 (body)
 * - IBM Plex Mono (code)
 */

${imports.join("\n")}
`

  const masterPath = path.join(OUTPUT_DIR, "fonts.css")
  await fs.writeFile(masterPath, masterCSS)
  console.log("✓ Generated fonts.css\n")
}

async function main() {
  console.log("🔤 Font Download Utility\n")
  console.log(`Output: ${OUTPUT_DIR}\n`)

  // Clean output directory
  await fs.rm(OUTPUT_DIR, { recursive: true, force: true })
  await fs.mkdir(OUTPUT_DIR, { recursive: true })

  // Download each font
  for (const font of FONTS) {
    await downloadFont(font)
  }

  // Generate master CSS
  await generateMasterCSS()

  console.log("✅ Font download complete!")
}

main().catch((error) => {
  console.error("❌ Font download failed:", error)
  process.exit(1)
})
